name: JPackage Windows

on:
  release:
    types: [ released, prereleased ]

jobs:
  gradle:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: desktop:packageMsi
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - uses: softprops/action-gh-release@v1
        with:
          files: desktop/build/compose/binaries/main/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
